dataset:
  train_path: E:\Code_Project\Artificial Intelligence\Detect_Malware_in_Android_using_deeplearning_B19DCAT208\dataset\graph\train
  val_path: E:\Code_Project\Artificial Intelligence\Detect_Malware_in_Android_using_deeplearning_B19DCAT208\dataset\graph\test

model:
  conv_count: 3
  conv_algorithm: GraphConv
  input_dimension: 353
  model_path: E:\Code_Project\Artificial Intelligence\Detect_Malware_in_Android_using_deeplearning_B19DCAT208\train_model\model
