dataset:
  train_path: D:\Code\Code Project\Detect_Malware_in_Android_using_deeplearning_B19DCAT208\Detect_Malware_in_Android_using_deeplearning_B19DCAT208\dataset\graph\train
  val_path: D:\Code\Code Project\Detect_Malware_in_Android_using_deeplearning_B19DCAT208\Detect_Malware_in_Android_using_deeplearning_B19DCAT208\dataset\graph\test

model:
  conv_count: 3
  conv_algorithm: SAGEConv
  input_dimension: 353
  model_path: D:\Code\Code Project\Detect_Malware_in_Android_using_deeplearning_B19DCAT208\Detect_Malware_in_Android_using_deeplearning_B19DCAT208\train_model\model
