data:
  train_dir: E:\Code_Project\Artificial Intelligence\Detect_Malware_in_Android_using_deeplearning_B19DCAT208\dataset\rdg\train
  test_dir: E:\Code_Project\Artificial Intelligence\Detect_Malware_in_Android_using_deeplearning_B19DCAT208\dataset\rdg\test
  batch_size: 16
  pin_memory: false
  num_workers: 6
  split_train_val: true
  split_ratios: [0.75, 0.25]
  consider_features: [function_name]

model:
  conv_count: 3
  conv_algorithm: GraphConv # Can be one of GraphConv, SAGEConv, TAGConv, SGConv, DotGatConv
  input_dimension: 100

trainer:
  max_epochs: 2

hydra:
  run:
    dir: output/${model.conv_algorithm}/${features.name}-conv_count=${model.conv_count}
  sweep:
    dir: output/${model.conv_algorithm}
    subdir: ${features.name}-conv_count=${model.conv_count}

defaults:
  - features: degree
  - logger: wandb
