dataset:
  train_path: E:\Code_Project\Artificial Intelligence\Detect_Malware_in_Android_using_deeplearning_B19DCAT208\dataset\rdg\train
  val_path: E:\Code_Project\Artificial Intelligence\Detect_Malware_in_Android_using_deeplearning_B19DCAT208\dataset\rdg\test
  ratios: [0.75, 0.25]

model:
  conv_count: 3
  conv_algorithm: GraphConv
  input_dimension: 100