data:
  train_dir: E:\Code_Project\Artificial Intelligence\Detect_Malware_in_Android_using_deeplearning_B19DCAT208\dataset\graph\train
  test_dir: E:\Code_Project\Artificial Intelligence\Detect_Malware_in_Android_using_deeplearning_B19DCAT208\dataset\graph\test
  batch_size: 16
  pin_memory: false
  num_workers: 6
  split_train_val: true
  split_ratios: [0.75, 0.25]
  consider_features: [
      external,
      # entrypoint,
      native,
      public,
      static,
      codesize,
      # api,
      # user,
      # center,
      # degree,
      # permissions,
    ]

model:
  convolution_count: 3
  convolution_algorithm: GraphConv # Can be one of GraphConv, SAGEConv, TAGConv, SGConv, DotGatConv
  input_dimension: 5

trainer:
  max_epochs: 100

hydra:
  run:
    dir: output/${model.convolution_algorithm}/${features.name}-conv_count=${model.convolution_count}
  sweep:
    dir: output/${model.convolution_algorithm}
    subdir: ${features.name}-conv_count=${model.convolution_count}

defaults:
  - features: degree
  - logger: wandb
